#!/bin/sh /etc/rc.common
# vpn-split procd init: применяет 3-зонную маршрутизацию и держит watchdog.
# Запускается ПОСЛЕ network и amneziawg, чтобы awg0 уже существовал.

USE_PROCD=1
START=95
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/vpn-split-enforce --watch
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	/usr/sbin/vpn-split-enforce
}

service_triggers() {
	procd_add_reload_trigger "vpn-split" "network" "firewall" "dhcp"
}
