#!/bin/bash
#
# Update Domains Script
# Обновляет конфигурацию dnsmasq на основе списка доменов
#

DOMAINS_FILE="/opt/vpn-gateway/vpn-domains.txt"
DNSMASQ_CONF="/etc/dnsmasq.d/domains.d/vpn-domains.conf"
IPSET_NAME="vpn_domains"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Создаём ipset если не существует
ensure_ipset() {
    if ! ipset list "$IPSET_NAME" &>/dev/null; then
        log "Creating ipset $IPSET_NAME"
        ipset create "$IPSET_NAME" hash:ip timeout 86400
    fi
}

# Генерируем конфигурацию dnsmasq
generate_dnsmasq_conf() {
    log "Generating dnsmasq configuration..."
    
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    
    {
        echo "# Auto-generated by update-domains.sh"
        echo "# Generated: $(date)"
        echo ""
        
        if [[ -f "$DOMAINS_FILE" ]]; then
            while IFS= read -r domain; do
                # Пропускаем пустые строки и комментарии
                [[ -z "$domain" || "$domain" =~ ^# ]] && continue
                
                # Trim whitespace
                domain=$(echo "$domain" | xargs)
                
                # dnsmasq ipset синтаксис
                echo "ipset=/${domain}/${IPSET_NAME}"
            done < "$DOMAINS_FILE"
        fi
    } > "$DNSMASQ_CONF"
    
    log "Configuration written to $DNSMASQ_CONF"
}

# Перезагружаем dnsmasq
reload_dnsmasq() {
    log "Reloading dnsmasq..."
    
    # Проверяем конфигурацию
    if dnsmasq --test 2>/dev/null; then
        systemctl reload dnsmasq
        log "dnsmasq reloaded successfully"
    else
        log "ERROR: dnsmasq configuration test failed!"
        return 1
    fi
}

# Показываем статистику
show_stats() {
    local domain_count=0
    local ip_count=0
    
    if [[ -f "$DOMAINS_FILE" ]]; then
        domain_count=$(grep -v '^#' "$DOMAINS_FILE" | grep -v '^$' | wc -l)
    fi
    
    if ipset list "$IPSET_NAME" &>/dev/null; then
        ip_count=$(ipset list "$IPSET_NAME" | grep -c "^[0-9]" || echo 0)
    fi
    
    log "Statistics: $domain_count domains, $ip_count IPs in ipset"
}

main() {
    log "=== Update Domains ==="
    
    ensure_ipset
    generate_dnsmasq_conf
    reload_dnsmasq
    show_stats
    
    log "=== Done ==="
}

main "$@"
